import { Recette } from './recette';
  
export const RECETTES: Recette[] = [
    {
        idRecette: 1,
        idUtilisateur: 1,
        titre: "Recette1",
        description: "description1",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 2,
        idUtilisateur: 2,
        titre: "Recette2",
        description: "description2",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 3,
        idUtilisateur: 3,
        titre: "Recette3",
        description: "description3",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 4,
        idUtilisateur: 1,
        titre: "Recette4",
        description: "description4",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 5,
        idUtilisateur: 2,
        titre: "Recette5",
        description: "description5",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 6,
        idUtilisateur: 3,
        titre: "Recette6",
        description: "description6",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 7,
        idUtilisateur: 1,
        titre: "Recette7",
        description: "description7",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 8,
        idUtilisateur: 2,
        titre: "Recette8",
        description: "description8",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 9,
        idUtilisateur: 3,
        titre: "Recette9",
        description: "description9",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 10,
        idUtilisateur: 1,
        titre: "Recette10",
        description: "description10",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 11,
        idUtilisateur: 2,
        titre: "Recette11",
        description: "description11",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 12,
        idUtilisateur: 3,
        titre: "Recette12",
        description: "description12",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 13,
        idUtilisateur: 1,
        titre: "Recette13",
        description: "description13",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 14,
        idUtilisateur: 2,
        titre: "Recette14",
        description: "description14",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 15,
        idUtilisateur: 3,
        titre: "Recette15",
        description: "description15",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 16,
        idUtilisateur: 1,
        titre: "Recette16",
        description: "description16",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 17,
        idUtilisateur: 2,
        titre: "Recette17",
        description: "description17",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 18,
        idUtilisateur: 3,
        titre: "Recette18",
        description: "description18",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 19,
        idUtilisateur: 1,
        titre: "Recette19",
        description: "description19",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 20,
        idUtilisateur: 2,
        titre: "Recette20",
        description: "description20",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 21,
        idUtilisateur: 3,
        titre: "Recette21",
        description: "description21",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 22,
        idUtilisateur: 1,
        titre: "Recette22",
        description: "description22",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 23,
        idUtilisateur: 2,
        titre: "Recette23",
        description: "description23",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 24,
        idUtilisateur: 3,
        titre: "Recette24",
        description: "description24",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },

];