import { Recette } from './recette';
  
export const RECETTES: Recette[] = [
    {
        idRecette: 1,
        idUtilisateur: 1,
        titre: "Recette1",
        description: "description1",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 2,
        idUtilisateur: 2,
        titre: "Recette2",
        description: "description2",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 3,
        idUtilisateur: 3,
        titre: "Recette3",
        description: "description3",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 4,
        idUtilisateur: 1,
        titre: "Recette4",
        description: "description4",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 5,
        idUtilisateur: 2,
        titre: "Recette5",
        description: "description5",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 6,
        idUtilisateur: 3,
        titre: "Recette6",
        description: "description6",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 7,
        idUtilisateur: 1,
        titre: "Recette7",
        description: "description7",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 8,
        idUtilisateur: 2,
        titre: "Recette8",
        description: "description8",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 9,
        idUtilisateur: 3,
        titre: "Recette9",
        description: "description9",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 10,
        idUtilisateur: 1,
        titre: "Recette10",
        description: "description10",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 11,
        idUtilisateur: 2,
        titre: "Recette11",
        description: "description11",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    {
        idRecette: 12,
        idUtilisateur: 3,
        titre: "Recette12",
        description: "description12",
        date: new Date(),
        imageRecette: "lien vers l'image",
    },
    

];